# Generated by Django 3.2.9 on 2021-12-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_lec_units',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_prac_units',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_units',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
