# Generated by Django 3.2.9 on 2021-12-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20211213_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_lec_units',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_prac_units',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='compre_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='compre_session',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='days_and_hours',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='room',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
